python mmfi_pose_quick.py train ^
  --packed-root "C:\Users\GSBME\SmartCupStudy\Unified_network\data_sets\MM-Fi\packed_data" ^
  --out "runs\mmfi_pose_anchor_v4" ^
  --split cross_environment ^
  --spatial-mode cloud_anchor ^
  --target-mode cloud_anchor_relative ^
  --signal-mode none ^
  --sample-period-sec 0.1 ^
  --epochs 25 ^
  --batch-size 128 ^
  --workers 4
